name: forcesocial
version: 0.0.1
author: Joris Hermans <hermansj@gmail.com>
description: A social connector part of the dart force framework
homepage: https://github.com/jorishermans/dart-forcesocial
dependencies:
  logging: '>=0.9.0 <0.10.0'
  forcemvc: '>=0.1.8+3 <0.2.0'
  yaml: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.10.1'
